
CREATE DATABASE EJERCICIOSSENCILLOS1

USE EJERCICIOSSENCILLOS1

CREATE TABLE AYUNTAMIENTOS(
 ID smallInt Not Null 
,CONSTRAINT PK_AYUNTAMIENTOS PRIMARY KEY(ID)
,Localidad Varchar(25) Not Null
,Provincia Varchar(25) Not Null
)

CREATE TABLE SECRETARIOS(
 ID smallInt Not Null 
,CONSTRAINT PK_SECRETARIOS PRIMARY KEY(ID)
,Nombre Varchar(35) Not Null
,Apellidos Varchar(35) Not Null
,fecha_de_alta date Not Null
,ID_Ayuntamiento smallInt Not Null
,CONSTRAINT FK_SECRETARIOS_AYUNTAMIENTOS FOREIGN KEY(ID_Ayuntamiento) 
REFERENCES AYUNTAMIENTOS(ID) ON DELETE NO ACTION ON UPDATE CASCADE
)

CREATE TABLE ALCALDES(
 ID smallInt Not Null 
,CONSTRAINT PK_ALCALDES PRIMARY KEY(ID)
,Nombre Varchar(35) Not Null
,Apellidos Varchar(35) Not Null
,fecha_de_alta date Not Null
,ID_Ayuntamiento smallInt Not Null
,CONSTRAINT FK_ALCALDES_AYUNTAMIENTOS FOREIGN KEY(ID_Ayuntamiento) 
REFERENCES AYUNTAMIENTOS(ID) ON DELETE NO ACTION ON UPDATE CASCADE
) 

DROP TABLE AYUNTAMIENTOS
DROP DATABASE EJERCICIOSSENCILLOS1